# Generated by Django 3.2.9 on 2021-12-23 00:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anotherapp', '0002_create_root_page'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherTest',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('field_that_is_not_translated', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='The main contents of the page', verbose_name='body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InheritsFromHomePageTranslated',
            fields=[
                ('homepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anotherapp.homepage')),
                ('title_da', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en_UK', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_nb', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('seo_title_da', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en_UK', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_de', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_nb', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('search_description_da', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en_UK', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_de', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_nb', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('field_that_is_translated', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_da', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en_UK', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_de', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_nb', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_not_translated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('anotherapp.homepage',),
        ),
        migrations.CreateModel(
            name='InheritsFromPageTranslated',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_da', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en_UK', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_nb', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('seo_title_da', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en_UK', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_de', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_nb', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('search_description_da', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en_UK', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_de', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_nb', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('field_that_is_translated', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_da', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en_UK', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_de', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_nb', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_not_translated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_da', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en_UK', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_de', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_nb', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('seo_title_da', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_en_UK', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_de', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('seo_title_nb', models.CharField(blank=True, help_text='The name of the page displayed on search engine results as the clickable headline.', max_length=255, null=True, verbose_name='title tag')),
                ('search_description_da', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_en_UK', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_de', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('search_description_nb', models.TextField(blank=True, help_text='The descriptive text displayed underneath a headline in search engine results.', null=True, verbose_name='meta description')),
                ('field_that_is_translated', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_da', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_en_UK', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_de', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_translated_nb', models.CharField(blank=True, max_length=255, null=True)),
                ('field_that_is_not_translated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
