# Config file for automatic testing at travis-ci.org

sudo: false
dist: trusty

env: PIP_DOWNLOAD_CACHE="pip_cache"

language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev

# See tox.ini for env list
env:
- TOXENV=py27
- TOXENV=py35
- TOXENV=style

install:
  - pip install tox>=2.1

script:
  - tox -e $TOXENV
