# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "2.7"

# See tox.ini for env list
env:
- TOXENV=py27
- TOXENV=py35

install:
  - pip install tox>=2.1

script:
  - tox -e $TOXENV
