# Config file for automatic testing at travis-ci.org

sudo: false

env: PIP_DOWNLOAD_CACHE="pip_cache"

language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install tox tox-travis

script:
  - tox
