# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
